### ISSUE TITLE
Design V1 website layout

### ISSUE THREAD

**Issue by matthova** [williamscs/SparkPrint#3]
I was thinking we should implement something simple. Just a header, body, footer sort of architecture.

The header would allow us to navigate between the following:
Printers
Jobs

hmmm.... I really think that's it.
Anyway, V1, lets just have a boring header and footer, and basic body that is dynamically populated without refreshing the page.

**Comment by williamscs** [comment]
We have the sample json for the status of a printer, but we'll also need the data for how we'll parse the available printers and current jobs.

**Comment by kaitlynhova** [comment]
Here are the original mockups for the MVP V1.
![sparkprint-original-mockups2](https://cloud.githubusercontent.com/assets/5474124/6999867/18a2a09c-dbdc-11e4-9eca-3ba19f65a59c.png)
